version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      cargo-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: uv
    directory: "/binoc-python"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: "/model-plugins/binoc-sqlite"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: "/model-plugins/binoc-html"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5