[workspace]
members = [
    "binoc-sdk",
    "binoc-core",
    "binoc-stdlib",
    "binoc-cli",
    "binoc-python",
    "model-plugins/binoc-sqlite",
    "model-plugins/binoc-row-reorder",
]
default-members = [
    "binoc-sdk",
    "binoc-core",
    "binoc-stdlib",
    "binoc-cli",
    "model-plugins/binoc-sqlite",
    "model-plugins/binoc-row-reorder",
]
resolver = "2"
