[package]
name = "binoc-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Core controller and host runtime for Binoc"
publish = false

[dependencies]
binoc-sdk = { workspace = true }
rayon = "1.11.0"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9.34"
tempfile = { workspace = true }

[dev-dependencies]
insta = "1.46.3"
toml = "1.0.4"
