[config]
comparators = [
  "binoc.zip",
  "binoc.tar",
  "binoc.directory",
  "binoc-stat-binary.stata",
  "binoc-stat-binary.sas7bdat",
  "binoc-stat-binary.xpt",
  "binoc.text",
  "binoc.binary",
]
transformers = ["binoc.tabular_analyzer", "binoc.column_reorder_detector"]
