from __future__ import annotations

from typing import Any, Iterator

AnnotationRecord = dict[str, Any]
SourceRecord = dict[str, Any]

class DiffNode:
    def __init__(
        self,
        action: str,
        item_type: str,
        path: str,
        *,
        sources: list[SourceRecord] | None = None,
        summary: str | None = None,
        tags: list[str] | set[str] | None = None,
        details: dict[str, Any] | None = None,
        annotations: list[AnnotationRecord] | None = None,
        children: list[DiffNode] | None = None,
    ) -> None: ...
    @property
    def action(self) -> str: ...
    @property
    def item_type(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def sources(self) -> list[SourceRecord]: ...
    @property
    def summary(self) -> str | None: ...
    @property
    def tags(self) -> list[str]: ...
    @property
    def children(self) -> list[DiffNode]: ...
    @property
    def details(self) -> dict[str, Any]: ...
    @property
    def annotations(self) -> list[AnnotationRecord]: ...
    def node_count(self) -> int: ...
    def all_tags(self) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def with_summary(self, summary: str) -> DiffNode: ...
    def with_tag(self, tag: str) -> DiffNode: ...
    def with_source(
        self,
        path: str,
        side: str,
        evidence: str | None,
        action: str | None,
    ) -> DiffNode: ...
    def with_children(self, children: list[DiffNode]) -> DiffNode: ...
    def with_detail(self, key: str, value: Any) -> DiffNode: ...
    def with_annotation_from(self, package: str, key: str, value: Any) -> DiffNode: ...
    def annotate_from(self, package: str, key: str, value: Any) -> DiffNode: ...
    def find_node(self, selector: str) -> DiffNode | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> DiffNode: ...
    def __iter__(self) -> Iterator[DiffNode]: ...
    def __bool__(self) -> bool: ...

class Changeset:
    def __init__(
        self,
        from_snapshot: str,
        to_snapshot: str,
        root: DiffNode | None = None,
    ) -> None: ...
    @property
    def from_snapshot(self) -> str: ...
    @property
    def to_snapshot(self) -> str: ...
    @property
    def root(self) -> DiffNode | None: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    @property
    def diagnostics(self) -> list[dict[str, Any]]: ...
    @property
    def claims(self) -> list[dict[str, Any]]: ...
    @property
    def node_count(self) -> int: ...
    def find_node(self, selector: str) -> DiffNode | None: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> Changeset: ...
    @staticmethod
    def from_file(path: str) -> Changeset: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...

class ItemPair:
    @staticmethod
    def both(
        left_path: str,
        right_path: str,
        left_logical: str = '',
        right_logical: str = '',
    ) -> ItemPair: ...
    @staticmethod
    def added(path: str, logical: str = '') -> ItemPair: ...
    @staticmethod
    def removed(path: str, logical: str = '') -> ItemPair: ...
    @property
    def left_path(self) -> str | None: ...
    @property
    def right_path(self) -> str | None: ...
    @property
    def logical_path(self) -> str: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def is_dir(self) -> bool: ...
    def __repr__(self) -> str: ...

class Config:
    def __init__(self) -> None: ...
    @staticmethod
    def default() -> Config: ...
    @staticmethod
    def from_file(path: str) -> Config: ...
    def __repr__(self) -> str: ...

class PluginRegistry:
    @staticmethod
    def default() -> PluginRegistry: ...
    def register_renderer(self, name: str, obj: Any) -> None: ...
    def load_native_plugin(self, module_path: str) -> None: ...
    def list_renderers(self) -> list[str]: ...
    def __repr__(self) -> str: ...

def diff(
    snapshot_a: str,
    snapshot_b: str,
    *,
    config: Config | None = None,
) -> Changeset: ...
def to_json(changeset: Changeset) -> str: ...
def to_markdown(
    changesets: list[Changeset],
    *,
    config: Config | None = None,
) -> str: ...
def extract(
    changeset: Changeset,
    node_path: str,
    aspect: str = 'content',
    *,
    snapshot_a: str | None = None,
    snapshot_b: str | None = None,
    config: Config | None = None,
) -> str: ...
def run_cli(registry: PluginRegistry, args: list[str]) -> None: ...
