from __future__ import annotations

from typing import Any, Iterator

class DiffNode:
    def __init__(
        self,
        action: str,
        item_type: str,
        path: str,
        *,
        source_path: str | None = None,
        summary: str | None = None,
        tags: list[str] | set[str] | None = None,
        details: dict[str, Any] | None = None,
        annotations: dict[str, Any] | None = None,
        children: list[DiffNode] | None = None,
    ) -> None: ...
    @property
    def action(self) -> str: ...
    @property
    def item_type(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def source_path(self) -> str | None: ...
    @property
    def summary(self) -> str | None: ...
    @property
    def tags(self) -> list[str]: ...
    @property
    def children(self) -> list[DiffNode]: ...
    @property
    def details(self) -> dict[str, Any]: ...
    @property
    def annotations(self) -> dict[str, Any]: ...
    def node_count(self) -> int: ...
    def all_tags(self) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def with_summary(self, summary: str) -> DiffNode: ...
    def with_tag(self, tag: str) -> DiffNode: ...
    def with_source_path(self, source: str) -> DiffNode: ...
    def with_children(self, children: list[DiffNode]) -> DiffNode: ...
    def with_detail(self, key: str, value: Any) -> DiffNode: ...
    def find_node(self, selector: str) -> DiffNode | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> DiffNode: ...
    def __iter__(self) -> Iterator[DiffNode]: ...
    def __bool__(self) -> bool: ...

class Changeset:
    def __init__(
        self,
        from_snapshot: str,
        to_snapshot: str,
        root: DiffNode | None = None,
    ) -> None: ...
    @property
    def from_snapshot(self) -> str: ...
    @property
    def to_snapshot(self) -> str: ...
    @property
    def root(self) -> DiffNode | None: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    @property
    def node_count(self) -> int: ...
    def find_node(self, selector: str) -> DiffNode | None: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> Changeset: ...
    @staticmethod
    def from_file(path: str) -> Changeset: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...

class ItemPair:
    @staticmethod
    def both(
        left_path: str,
        right_path: str,
        left_logical: str = '',
        right_logical: str = '',
    ) -> ItemPair: ...
    @staticmethod
    def added(path: str, logical: str = '') -> ItemPair: ...
    @staticmethod
    def removed(path: str, logical: str = '') -> ItemPair: ...
    @property
    def left_path(self) -> str | None: ...
    @property
    def right_path(self) -> str | None: ...
    @property
    def logical_path(self) -> str: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def is_dir(self) -> bool: ...
    def __repr__(self) -> str: ...

class Config:
    def __init__(
        self,
        *,
        comparators: list[str] | None = None,
        transformers: list[str] | None = None,
    ) -> None: ...
    @staticmethod
    def default() -> Config: ...
    @staticmethod
    def from_file(path: str) -> Config: ...
    def add_comparator(self, comparator: Any) -> None: ...
    def add_transformer(self, transformer: Any) -> None: ...
    @property
    def comparators(self) -> list[str]: ...
    @property
    def transformers(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class PluginRegistry:
    @staticmethod
    def default() -> PluginRegistry: ...
    def register_comparator(self, name: str, obj: Any) -> None: ...
    def register_transformer(self, name: str, obj: Any) -> None: ...
    def register_renderer(self, name: str, obj: Any) -> None: ...
    def load_native_plugin(self, module_path: str) -> None: ...
    def list_comparators(self) -> list[str]: ...
    def list_transformers(self) -> list[str]: ...
    def list_renderers(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class Identical:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class Leaf:
    node: DiffNode
    def __init__(self, node: DiffNode) -> None: ...
    def __repr__(self) -> str: ...

class Expand:
    node: DiffNode
    children: list[ItemPair]
    def __init__(self, node: DiffNode, children: list[ItemPair]) -> None: ...
    def __repr__(self) -> str: ...

class Unchanged:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class Replace:
    node: DiffNode
    def __init__(self, node: DiffNode) -> None: ...
    def __repr__(self) -> str: ...

class ReplaceMany:
    nodes: list[DiffNode]
    def __init__(self, nodes: list[DiffNode]) -> None: ...
    def __repr__(self) -> str: ...

class Remove:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

def diff(
    snapshot_a: str,
    snapshot_b: str,
    *,
    config: Config | None = None,
    registry: PluginRegistry | None = None,
) -> Changeset: ...
def to_json(changeset: Changeset) -> str: ...
def to_markdown(
    changesets: list[Changeset],
    *,
    config: Config | None = None,
) -> str: ...
def extract(
    changeset: Changeset,
    node_path: str,
    aspect: str = 'content',
    *,
    snapshot_a: str | None = None,
    snapshot_b: str | None = None,
    config: Config | None = None,
) -> str: ...
def run_cli(registry: PluginRegistry, args: list[str]) -> None: ...
