[package]
name = "binoc-python"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "PyO3 bindings and Python CLI host for Binoc"
publish = false

[lib]
name = "_binoc"
crate-type = ["cdylib"]

[dependencies]
binoc-core = { workspace = true }
binoc-sdk = { workspace = true }
binoc-stdlib = { workspace = true }
binoc-cli = { workspace = true }
libloading = "0.9"
pyo3 = { workspace = true }
serde_json = { workspace = true }
